### PR TITLE
Fix post an issue & submit a PR links

### PR DESCRIPTION
**Pull request by andylolz**
Refs #148.

### CODE REVIEW

**Comment by andylolz** [comment]
I guess the PR link should be something like:

```
https://github.com/org-id/register/tree/{{ branch }}/lists/{{ org_list.coverage.first }}/{{ org_list.code }}.json
```

…but that’s not quite right.

**Comment by timgdavies** [comment]
@andylolz This looks good - and a good fix for now. There's a branch I'm working on where I hope to introduce an editing interface in near future - but not quite ready. 

@Bjwebb Can you see why the Travis tests are failing on this and whether we can get this merge-able?

**Comment by andylolz** [comment]
Tests pass for me locally.

**Comment by Bjwebb** [comment]
Tests fail due to travis IPs having hit the limit for github api requests.
I've added an API key so the tests pass for our pushes, but travis doesn't trust other people's pull requests with that key.

I've triggered a push run on travis and it passes. It's okay to merge this pull request.

**Comment by andylolz** [comment]
@Bjwebb I guess you could `git commit --amend --no-edit && git push -f origin` to force a green tick here? Would that work?

**Comment by Bjwebb** [comment]
Deployed now to http://org-id.guide/

**Pull request merged**
