### PR TITLE
fallback link where no id guidance & country code abbreviations

### PR DESCRIPTION
**Pull request by BobHarper1**
It took me a few visits to notice the link to publisher website at the top right of title.

For lists that don't have as much information, it might be better to provide the user a link to the website where they expect to find something e.g. under 'Find identifiers'. So if there is no guidance (`access.guidanceOnLocatingIds`) just present a link to the `url` (instead of 'None')

image

### CODE REVIEW

**Comment by BobHarper1** [comment]
Also, on my small laptop screen (1280px x 581px viewport), the footer hides the bottom of the homepage form (hides more of it with less height again)

image

[Changing the `@media` rule to a wider width (`100em`)](https://github.com/OpenDataServices/org-ids/pull/165/commits/7780d17628a4c0778fd18b30afaf4998ed61c84f) fixes this, for me, but I appreciate that might be a problem with other viewports.

**Comment by andylolz** [comment]
Refs #152.

@BobHarper1: This looks similar to #158. I get the impression from the discussion there that there are data issues preventing this from being fixed :(

**Comment by andylolz** [comment]
> Also, on my small laptop screen (1280px x 581px viewport), the footer hides the bottom of the homepage form (hides more of it with less height again)

@BobHarper1: See #133. Looks to me like @Bjwebb has fixed it on staging.

**Comment by BobHarper1** [comment]
Whoops, great.

**Comment by Bjwebb** [comment]
> @BobHarper1: See #133. Looks to me like @Bjwebb has fixed it on staging.

That fix has also been on the live site for a while now, so I think @BobHarper1's bug still exist for even smaller screens.

**Comment by andylolz** [comment]
> That fix has also been on the live site for a while now, so I think @BobHarper1's bug still exist for even smaller screens.

Oh, you’re quite right! But can I suggest moving further discussion about that to #133?

**Comment by Bjwebb** [comment]
This was merged accidentally, so I've undone with a reset.

New pull request at https://github.com/OpenDataServices/org-ids/pull/175

**Pull request merged**
