### PR TITLE
Split register and preview

### PR DESCRIPTION
**Pull request by timgdavies**
An updated pull request based on feedback from Rob Redpath with a cleaner commit history.

### CODE REVIEW

**Comment by robredpath** [comment]
Looking good, and I've got the tests working as well. 

The only major thing left is that we don't sanitise the branch input, which we use in a lot of places. That scares me. I think the best place to do that is in the regex in urls.py - I think we can sensibly specify that branch names must be A-Za-z0-9- , and anything else just gets ignored. Does that work for you @timgdavies ? Can you make that change?

**Comment by timgdavies** [comment]
@robredpath Would you be able to make that RegEx change? I've not had great luck with my path writing to date...  If not - I can try late tomorrow.

**Comment by robredpath** [comment]
Done!

**Comment by robredpath** [comment]
@timgdavies On my final look at this, I saw that you describe the new repo as not yet authoritative - will that change when we deploy these changes, or do we need to hold off deploying at all?

**Comment by robredpath** [comment]
Great, thanks @timgdavies . Merged, and over to @Bjwebb to deploy.

**Comment by Bjwebb** [comment]
Deployed now http://org-id.guide/

**Pull request merged**
