### PR TITLE
Update for Poland

### PR DESCRIPTION
**Pull request by KrzysztofMadejski**
I'm sending this Pull Request to signal we want to update information on Polish register. Since there is no schema or guide what the fields mean I'm putting it on hold. Please ping when it will be possible to collaborate.

### CODE REVIEW

**Comment by timgdavies** [comment]
Thanks @KrzysztofMadejski - That was quick! As [mentioned here](https://identify-org.net/2016/11/28/managing-our-list-of-lists-on-github/) we'll work on a schema very soon - and will ping soon.

**Comment by timgdavies** [comment]
I'll merge this via #79  - working on getting the project tidier for further updates in the coming weeks.

**Comment by KrzysztofMadejski** [comment]
Should we input any information on Poland now, or you will be reaching out later to country leads?

**Comment by timgdavies** [comment]
Hey @KrzysztofMadejski If you want to open issues, or submit pull requests using the new schema - that would be most welcome.

**Pull request closed without merging**
